### PR TITLE
Bump version from 5.1.0 to 5.2.0

### PR DESCRIPTION
**Pull request by sshquack**
Thank you for quickly reviewing and merging PR #2, @heynemann! I forgot to bump the version earlier. 

Could you please release a new version to PyPI after merging this? Soon after that I'll create a PR for both of these:
- Thumbor config docs - https://github.com/thumbor/thumbor/blob/master/docs/configuration.rst
- Apsl thumbor image - https://github.com/APSL/docker-thumbor/blob/master/thumbor/requirements.txt

### CODE REVIEW

**Comment by sshquack** [comment]
@heynemann Since I don't have a Slack invite, I'm unable to reach the Thumbor dev team. Is there some way that I can help you with in getting this version published?

**Comment by heynemann** [comment]
I don't think I'm responsible for this project in pypi. Maybe @masom can help?

**Comment by heynemann** [comment]
Sorry, actually I am, lol

**Comment by masom** [comment]
I'll merge this but @heynemann will have to push or add more maintainers

**Comment by heynemann** [comment]
@masom Sorry for the long wait. You have been added as maintainer of thumbor-memcached in pypi! Sorry guys!

**Pull request merged**
